from __future__ import unicode_literals
from django.db import models
from django_unixdatetimefield import UnixDateTimeField


class Meta:
    app_label = 'atlas'


class Requests(models.Model):
    reqKw = models.TextField(null=False, blank=False)
    reqTime = models.DateTimeField(null=True, blank=True)
    reqStatus = models.TextField(null=True, blank=True)

    def __unicode__(self):
        return unicode(self.id)


class Product(models.Model):
    pid = models.CharField(max_length=100, primary_key=True)
    pCategory = models.CharField(max_length=255)
    pBrand = models.CharField(max_length=30)
    pDescr = models.TextField()
    pRating = models.DecimalField(max_digits=2, decimal_places=1)
    pImgSrc = models.TextField()
    pModel = models.CharField(max_length=30)
    pTitle = models.TextField()
    pURL = models.TextField()
    pPrice = models.CharField(max_length=10)
    siteCode = models.CharField(max_length=2)

    def __unicode__(self):
        return unicode(self.pTitle)


class Review(models.Model):
    rid = models.CharField(primary_key=True, max_length=100)
    rDate = UnixDateTimeField()
    rDate2 = models.DateField(null=True, blank=True)
    rRating = models.DecimalField(max_digits=2, decimal_places=1)
    rText = models.TextField()
    rTitle = models.TextField()
    rURL = models.TextField()
    rUser = models.CharField(max_length=30)
    pid = models.ForeignKey(Product, on_delete=models.CASCADE)
    dt = models.CharField(max_length=2, blank=True, null=True)
    mth = models.CharField(max_length=2, blank=True, null=True)
    year = models.CharField(max_length=4, blank=True, null=True)

    def __unicode__(self):
        return unicode(self.rTitle)


class Analysis(models.Model):
    sentiment = models.CharField(max_length=20, blank=True, null=True)
    sentiScore = models.DecimalField(max_digits=4, decimal_places=2, blank=True, null=True)
    trigger = models.CharField(max_length=200, blank=True, null=True)
    driver = models.CharField(max_length=200, blank=True, null=True)
    rid = models.ForeignKey(Review, on_delete=models.CASCADE)

    def __unicode__(self):
        return unicode(self.id)


class ContentCategoryRev(models.Model):
    category_pri = models.CharField(max_length=200, blank=True, null=True)
    category_sec = models.CharField(max_length=200, blank=True, null=True)
    category_ter = models.CharField(max_length=200, blank=True, null=True)
    confidence = models.DecimalField(max_digits=4, decimal_places=2, blank=True, null=True)
    rid = models.ForeignKey(Review, on_delete=models.CASCADE)

    def __unicode__(self):
        return unicode(self.id)


class DimenMap(models.Model):
    dict_filename = models.CharField(primary_key=True, max_length=255)
    dim1 = models.TextField(blank=True, null=True)
    d1_l1 = models.TextField(blank=True, null=True)
    d1_l2 = models.TextField(blank=True, null=True)
    d1_l3 = models.TextField(blank=True, null=True)
    d1_l4 = models.TextField(blank=True, null=True)
    d1_l5 = models.TextField(blank=True, null=True)
    dim2 = models.TextField(blank=True, null=True)
    d2_l1 = models.TextField(blank=True, null=True)
    d2_l2 = models.TextField(blank=True, null=True)
    d2_l3 = models.TextField(blank=True, null=True)
    d2_l4 = models.TextField(blank=True, null=True)
    d2_l5 = models.TextField(blank=True, null=True)
    dim3 = models.TextField(blank=True, null=True)
    d3_l1 = models.TextField(blank=True, null=True)
    d3_l2 = models.TextField(blank=True, null=True)
    d3_l3 = models.TextField(blank=True, null=True)
    d3_l4 = models.TextField(blank=True, null=True)
    d3_l5 = models.TextField(blank=True, null=True)
    dim4 = models.TextField(blank=True, null=True)
    d4_l1 = models.TextField(blank=True, null=True)
    d4_l2 = models.TextField(blank=True, null=True)
    d4_l3 = models.TextField(blank=True, null=True)
    d4_l4 = models.TextField(blank=True, null=True)
    d4_l5 = models.TextField(blank=True, null=True)
    dim5 = models.TextField(blank=True, null=True)
    d5_l1 = models.TextField(blank=True, null=True)
    d5_l2 = models.TextField(blank=True, null=True)
    d5_l3 = models.TextField(blank=True, null=True)
    d5_l4 = models.TextField(blank=True, null=True)
    d5_l5 = models.TextField(blank=True, null=True)
    dim6 = models.TextField(blank=True, null=True)
    d6_l1 = models.TextField(blank=True, null=True)
    d6_l2 = models.TextField(blank=True, null=True)
    d6_l3 = models.TextField(blank=True, null=True)
    d6_l4 = models.TextField(blank=True, null=True)
    d6_l5 = models.TextField(blank=True, null=True)
    dim7 = models.TextField(blank=True, null=True)
    d7_l1 = models.TextField(blank=True, null=True)
    d7_l2 = models.TextField(blank=True, null=True)
    d7_l3 = models.TextField(blank=True, null=True)
    d7_l4 = models.TextField(blank=True, null=True)
    d7_l5 = models.TextField(blank=True, null=True)
    dim8 = models.TextField(blank=True, null=True)
    d8_l1 = models.TextField(blank=True, null=True)
    d8_l2 = models.TextField(blank=True, null=True)
    d8_l3 = models.TextField(blank=True, null=True)
    d8_l4 = models.TextField(blank=True, null=True)
    d8_l5 = models.TextField(blank=True, null=True)
    dim9 = models.TextField(blank=True, null=True)
    d9_l1 = models.TextField(blank=True, null=True)
    d9_l2 = models.TextField(blank=True, null=True)
    d9_l3 = models.TextField(blank=True, null=True)
    d9_l4 = models.TextField(blank=True, null=True)
    d9_l5 = models.TextField(blank=True, null=True)
    dim10 = models.TextField(blank=True, null=True)
    d10_l1 = models.TextField(blank=True, null=True)
    d10_l2 = models.TextField(blank=True, null=True)
    d10_l3 = models.TextField(blank=True, null=True)
    d10_l4 = models.TextField(blank=True, null=True)
    d10_l5 = models.TextField(blank=True, null=True)
    dim11 = models.TextField(blank=True, null=True)
    d11_l1 = models.TextField(blank=True, null=True)
    d11_l2 = models.TextField(blank=True, null=True)
    d11_l3 = models.TextField(blank=True, null=True)
    d11_l4 = models.TextField(blank=True, null=True)
    d11_l5 = models.TextField(blank=True, null=True)
    dim12 = models.TextField(blank=True, null=True)
    d12_l1 = models.TextField(blank=True, null=True)
    d12_l2 = models.TextField(blank=True, null=True)
    d12_l3 = models.TextField(blank=True, null=True)
    d12_l4 = models.TextField(blank=True, null=True)
    d12_l5 = models.TextField(blank=True, null=True)
    dim13 = models.TextField(blank=True, null=True)
    d13_l1 = models.TextField(blank=True, null=True)
    d13_l2 = models.TextField(blank=True, null=True)
    d13_l3 = models.TextField(blank=True, null=True)
    d13_l4 = models.TextField(blank=True, null=True)
    d13_l5 = models.TextField(blank=True, null=True)
    dim14 = models.TextField(blank=True, null=True)
    d14_l1 = models.TextField(blank=True, null=True)
    d14_l2 = models.TextField(blank=True, null=True)
    d14_l3 = models.TextField(blank=True, null=True)
    d14_l4 = models.TextField(blank=True, null=True)
    d14_l5 = models.TextField(blank=True, null=True)
    dim15 = models.TextField(blank=True, null=True)
    d15_l1 = models.TextField(blank=True, null=True)
    d15_l2 = models.TextField(blank=True, null=True)
    d15_l3 = models.TextField(blank=True, null=True)
    d15_l4 = models.TextField(blank=True, null=True)
    d15_l5 = models.TextField(blank=True, null=True)


class TaggedDataRev(models.Model):
    dim1 = models.TextField(blank=True, null=True)
    d1_l1 = models.TextField(blank=True, null=True)
    d1_l2 = models.TextField(blank=True, null=True)
    d1_l3 = models.TextField(blank=True, null=True)
    d1_l4 = models.TextField(blank=True, null=True)
    d1_l5 = models.TextField(blank=True, null=True)
    dim2 = models.TextField(blank=True, null=True)
    d2_l1 = models.TextField(blank=True, null=True)
    d2_l2 = models.TextField(blank=True, null=True)
    d2_l3 = models.TextField(blank=True, null=True)
    d2_l4 = models.TextField(blank=True, null=True)
    d2_l5 = models.TextField(blank=True, null=True)
    dim3 = models.TextField(blank=True, null=True)
    d3_l1 = models.TextField(blank=True, null=True)
    d3_l2 = models.TextField(blank=True, null=True)
    d3_l3 = models.TextField(blank=True, null=True)
    d3_l4 = models.TextField(blank=True, null=True)
    d3_l5 = models.TextField(blank=True, null=True)
    dim4 = models.TextField(blank=True, null=True)
    d4_l1 = models.TextField(blank=True, null=True)
    d4_l2 = models.TextField(blank=True, null=True)
    d4_l3 = models.TextField(blank=True, null=True)
    d4_l4 = models.TextField(blank=True, null=True)
    d4_l5 = models.TextField(blank=True, null=True)
    dim5 = models.TextField(blank=True, null=True)
    d5_l1 = models.TextField(blank=True, null=True)
    d5_l2 = models.TextField(blank=True, null=True)
    d5_l3 = models.TextField(blank=True, null=True)
    d5_l4 = models.TextField(blank=True, null=True)
    d5_l5 = models.TextField(blank=True, null=True)
    dim6 = models.TextField(blank=True, null=True)
    d6_l1 = models.TextField(blank=True, null=True)
    d6_l2 = models.TextField(blank=True, null=True)
    d6_l3 = models.TextField(blank=True, null=True)
    d6_l4 = models.TextField(blank=True, null=True)
    d6_l5 = models.TextField(blank=True, null=True)
    dim7 = models.TextField(blank=True, null=True)
    d7_l1 = models.TextField(blank=True, null=True)
    d7_l2 = models.TextField(blank=True, null=True)
    d7_l3 = models.TextField(blank=True, null=True)
    d7_l4 = models.TextField(blank=True, null=True)
    d7_l5 = models.TextField(blank=True, null=True)
    dim8 = models.TextField(blank=True, null=True)
    d8_l1 = models.TextField(blank=True, null=True)
    d8_l2 = models.TextField(blank=True, null=True)
    d8_l3 = models.TextField(blank=True, null=True)
    d8_l4 = models.TextField(blank=True, null=True)
    d8_l5 = models.TextField(blank=True, null=True)
    dim9 = models.TextField(blank=True, null=True)
    d9_l1 = models.TextField(blank=True, null=True)
    d9_l2 = models.TextField(blank=True, null=True)
    d9_l3 = models.TextField(blank=True, null=True)
    d9_l4 = models.TextField(blank=True, null=True)
    d9_l5 = models.TextField(blank=True, null=True)
    dim10 = models.TextField(blank=True, null=True)
    d10_l1 = models.TextField(blank=True, null=True)
    d10_l2 = models.TextField(blank=True, null=True)
    d10_l3 = models.TextField(blank=True, null=True)
    d10_l4 = models.TextField(blank=True, null=True)
    d10_l5 = models.TextField(blank=True, null=True)
    dim11 = models.TextField(blank=True, null=True)
    d11_l1 = models.TextField(blank=True, null=True)
    d11_l2 = models.TextField(blank=True, null=True)
    d11_l3 = models.TextField(blank=True, null=True)
    d11_l4 = models.TextField(blank=True, null=True)
    d11_l5 = models.TextField(blank=True, null=True)
    dim12 = models.TextField(blank=True, null=True)
    d12_l1 = models.TextField(blank=True, null=True)
    d12_l2 = models.TextField(blank=True, null=True)
    d12_l3 = models.TextField(blank=True, null=True)
    d12_l4 = models.TextField(blank=True, null=True)
    d12_l5 = models.TextField(blank=True, null=True)
    dim13 = models.TextField(blank=True, null=True)
    d13_l1 = models.TextField(blank=True, null=True)
    d13_l2 = models.TextField(blank=True, null=True)
    d13_l3 = models.TextField(blank=True, null=True)
    d13_l4 = models.TextField(blank=True, null=True)
    d13_l5 = models.TextField(blank=True, null=True)
    dim14 = models.TextField(blank=True, null=True)
    d14_l1 = models.TextField(blank=True, null=True)
    d14_l2 = models.TextField(blank=True, null=True)
    d14_l3 = models.TextField(blank=True, null=True)
    d14_l4 = models.TextField(blank=True, null=True)
    d14_l5 = models.TextField(blank=True, null=True)
    dim15 = models.TextField(blank=True, null=True)
    d15_l1 = models.TextField(blank=True, null=True)
    d15_l2 = models.TextField(blank=True, null=True)
    d15_l3 = models.TextField(blank=True, null=True)
    d15_l4 = models.TextField(blank=True, null=True)
    d15_l5 = models.TextField(blank=True, null=True)
    rid = models.ForeignKey(Review, on_delete=models.CASCADE)
    pCategory = models.CharField(max_length=255, null=False)
    ngram = models.CharField(max_length=155, blank=True, null=True)
    dict_filename = models.ForeignKey(DimenMap, on_delete=models.CASCADE)

    def __unicode__(self):
        return unicode(self.id)


class AggTaggedDataRev(models.Model):
    pCategory = models.CharField(max_length=255, null=False)
    dim1 = models.TextField(blank=True, null=True)
    dim2 = models.TextField(blank=True, null=True)
    dim3 = models.TextField(blank=True, null=True)
    dim4 = models.TextField(blank=True, null=True)
    dim5 = models.TextField(blank=True, null=True)
    dim6 = models.TextField(blank=True, null=True)
    dim7 = models.TextField(blank=True, null=True)
    dim8 = models.TextField(blank=True, null=True)
    dim9 = models.TextField(blank=True, null=True)
    dim10 = models.TextField(blank=True, null=True)
    dim11 = models.TextField(blank=True, null=True)
    dim12 = models.TextField(blank=True, null=True)
    dim13 = models.TextField(blank=True, null=True)
    dim14 = models.TextField(blank=True, null=True)
    dim15 = models.TextField(blank=True, null=True)
    rid = models.ForeignKey(Review, on_delete=models.CASCADE)

    def __unicode__(self):
        return unicode(self.id)


class Uploads(models.Model):
    rid = models.CharField(max_length=100, primary_key=True)
    rDate = UnixDateTimeField(null=True, blank=True)
    rDate2 = models.DateField(null=True, blank=True)
    rRating = models.DecimalField(max_digits=2, decimal_places=1, null=True, blank=True)
    rText = models.TextField()
    rTitle = models.TextField(null=True, blank=True)
    rURL = models.TextField(null=True, blank=True)
    rUser = models.CharField(max_length=30, null=True, blank=True)
    pCategory = models.CharField(max_length=255)
    dt = models.CharField(max_length=2, blank=True, null=True)
    mth = models.CharField(max_length=2, blank=True, null=True)
    year = models.CharField(max_length=4, blank=True, null=True)

    def __unicode__(self):
        return unicode(self.rTitle)


class UploadAnalyses(models.Model):
    sentiment = models.CharField(max_length=20, null=True, blank=True)
    sentiScore = models.DecimalField(max_digits=4, decimal_places=2, null=True, blank=True)
    trigger = models.CharField(max_length=200, null=True, blank=True)
    driver = models.CharField(max_length=200, null=True, blank=True)
    rid = models.ForeignKey(Uploads, on_delete=models.CASCADE)

    def __unicode__(self):
        return unicode(self.id)


class ContentCategoryUpl(models.Model):
    category_pri = models.CharField(max_length=200, null=True, blank=True)
    category_sec = models.CharField(max_length=200, null=True, blank=True)
    category_ter = models.CharField(max_length=200, null=True, blank=True)
    confidence = models.DecimalField(max_digits=4, decimal_places=2, null=True, blank=True)
    rid = models.ForeignKey(Uploads, on_delete=models.CASCADE)

    def __unicode__(self):
        return unicode(self.id)


class DimenMapUpl(models.Model):
    dict_filename = models.CharField(max_length=255, primary_key=True)
    dim1 = models.TextField(blank=True, null=True)
    d1_l1 = models.TextField(blank=True, null=True)
    d1_l2 = models.TextField(blank=True, null=True)
    d1_l3 = models.TextField(blank=True, null=True)
    d1_l4 = models.TextField(blank=True, null=True)
    d1_l5 = models.TextField(blank=True, null=True)
    dim2 = models.TextField(blank=True, null=True)
    d2_l1 = models.TextField(blank=True, null=True)
    d2_l2 = models.TextField(blank=True, null=True)
    d2_l3 = models.TextField(blank=True, null=True)
    d2_l4 = models.TextField(blank=True, null=True)
    d2_l5 = models.TextField(blank=True, null=True)
    dim3 = models.TextField(blank=True, null=True)
    d3_l1 = models.TextField(blank=True, null=True)
    d3_l2 = models.TextField(blank=True, null=True)
    d3_l3 = models.TextField(blank=True, null=True)
    d3_l4 = models.TextField(blank=True, null=True)
    d3_l5 = models.TextField(blank=True, null=True)
    dim4 = models.TextField(blank=True, null=True)
    d4_l1 = models.TextField(blank=True, null=True)
    d4_l2 = models.TextField(blank=True, null=True)
    d4_l3 = models.TextField(blank=True, null=True)
    d4_l4 = models.TextField(blank=True, null=True)
    d4_l5 = models.TextField(blank=True, null=True)
    dim5 = models.TextField(blank=True, null=True)
    d5_l1 = models.TextField(blank=True, null=True)
    d5_l2 = models.TextField(blank=True, null=True)
    d5_l3 = models.TextField(blank=True, null=True)
    d5_l4 = models.TextField(blank=True, null=True)
    d5_l5 = models.TextField(blank=True, null=True)
    dim6 = models.TextField(blank=True, null=True)
    d6_l1 = models.TextField(blank=True, null=True)
    d6_l2 = models.TextField(blank=True, null=True)
    d6_l3 = models.TextField(blank=True, null=True)
    d6_l4 = models.TextField(blank=True, null=True)
    d6_l5 = models.TextField(blank=True, null=True)
    dim7 = models.TextField(blank=True, null=True)
    d7_l1 = models.TextField(blank=True, null=True)
    d7_l2 = models.TextField(blank=True, null=True)
    d7_l3 = models.TextField(blank=True, null=True)
    d7_l4 = models.TextField(blank=True, null=True)
    d7_l5 = models.TextField(blank=True, null=True)
    dim8 = models.TextField(blank=True, null=True)
    d8_l1 = models.TextField(blank=True, null=True)
    d8_l2 = models.TextField(blank=True, null=True)
    d8_l3 = models.TextField(blank=True, null=True)
    d8_l4 = models.TextField(blank=True, null=True)
    d8_l5 = models.TextField(blank=True, null=True)
    dim9 = models.TextField(blank=True, null=True)
    d9_l1 = models.TextField(blank=True, null=True)
    d9_l2 = models.TextField(blank=True, null=True)
    d9_l3 = models.TextField(blank=True, null=True)
    d9_l4 = models.TextField(blank=True, null=True)
    d9_l5 = models.TextField(blank=True, null=True)
    dim10 = models.TextField(blank=True, null=True)
    d10_l1 = models.TextField(blank=True, null=True)
    d10_l2 = models.TextField(blank=True, null=True)
    d10_l3 = models.TextField(blank=True, null=True)
    d10_l4 = models.TextField(blank=True, null=True)
    d10_l5 = models.TextField(blank=True, null=True)
    dim11 = models.TextField(blank=True, null=True)
    d11_l1 = models.TextField(blank=True, null=True)
    d11_l2 = models.TextField(blank=True, null=True)
    d11_l3 = models.TextField(blank=True, null=True)
    d11_l4 = models.TextField(blank=True, null=True)
    d11_l5 = models.TextField(blank=True, null=True)
    dim12 = models.TextField(blank=True, null=True)
    d12_l1 = models.TextField(blank=True, null=True)
    d12_l2 = models.TextField(blank=True, null=True)
    d12_l3 = models.TextField(blank=True, null=True)
    d12_l4 = models.TextField(blank=True, null=True)
    d12_l5 = models.TextField(blank=True, null=True)
    dim13 = models.TextField(blank=True, null=True)
    d13_l1 = models.TextField(blank=True, null=True)
    d13_l2 = models.TextField(blank=True, null=True)
    d13_l3 = models.TextField(blank=True, null=True)
    d13_l4 = models.TextField(blank=True, null=True)
    d13_l5 = models.TextField(blank=True, null=True)
    dim14 = models.TextField(blank=True, null=True)
    d14_l1 = models.TextField(blank=True, null=True)
    d14_l2 = models.TextField(blank=True, null=True)
    d14_l3 = models.TextField(blank=True, null=True)
    d14_l4 = models.TextField(blank=True, null=True)
    d14_l5 = models.TextField(blank=True, null=True)
    dim15 = models.TextField(blank=True, null=True)
    d15_l1 = models.TextField(blank=True, null=True)
    d15_l2 = models.TextField(blank=True, null=True)
    d15_l3 = models.TextField(blank=True, null=True)
    d15_l4 = models.TextField(blank=True, null=True)
    d15_l5 = models.TextField(blank=True, null=True)


class TagDictsUpl(models.Model):
    ngram = models.CharField(max_length=155)
    dim1 = models.TextField(blank=True, null=True)
    d1_l1 = models.TextField(blank=True, null=True)
    d1_l2 = models.TextField(blank=True, null=True)
    d1_l3 = models.TextField(blank=True, null=True)
    d1_l4 = models.TextField(blank=True, null=True)
    d1_l5 = models.TextField(blank=True, null=True)
    dim2 = models.TextField(blank=True, null=True)
    d2_l1 = models.TextField(blank=True, null=True)
    d2_l2 = models.TextField(blank=True, null=True)
    d2_l3 = models.TextField(blank=True, null=True)
    d2_l4 = models.TextField(blank=True, null=True)
    d2_l5 = models.TextField(blank=True, null=True)
    dim3 = models.TextField(blank=True, null=True)
    d3_l1 = models.TextField(blank=True, null=True)
    d3_l2 = models.TextField(blank=True, null=True)
    d3_l3 = models.TextField(blank=True, null=True)
    d3_l4 = models.TextField(blank=True, null=True)
    d3_l5 = models.TextField(blank=True, null=True)
    dim4 = models.TextField(blank=True, null=True)
    d4_l1 = models.TextField(blank=True, null=True)
    d4_l2 = models.TextField(blank=True, null=True)
    d4_l3 = models.TextField(blank=True, null=True)
    d4_l4 = models.TextField(blank=True, null=True)
    d4_l5 = models.TextField(blank=True, null=True)
    dim5 = models.TextField(blank=True, null=True)
    d5_l1 = models.TextField(blank=True, null=True)
    d5_l2 = models.TextField(blank=True, null=True)
    d5_l3 = models.TextField(blank=True, null=True)
    d5_l4 = models.TextField(blank=True, null=True)
    d5_l5 = models.TextField(blank=True, null=True)
    dim6 = models.TextField(blank=True, null=True)
    d6_l1 = models.TextField(blank=True, null=True)
    d6_l2 = models.TextField(blank=True, null=True)
    d6_l3 = models.TextField(blank=True, null=True)
    d6_l4 = models.TextField(blank=True, null=True)
    d6_l5 = models.TextField(blank=True, null=True)
    dim7 = models.TextField(blank=True, null=True)
    d7_l1 = models.TextField(blank=True, null=True)
    d7_l2 = models.TextField(blank=True, null=True)
    d7_l3 = models.TextField(blank=True, null=True)
    d7_l4 = models.TextField(blank=True, null=True)
    d7_l5 = models.TextField(blank=True, null=True)
    dim8 = models.TextField(blank=True, null=True)
    d8_l1 = models.TextField(blank=True, null=True)
    d8_l2 = models.TextField(blank=True, null=True)
    d8_l3 = models.TextField(blank=True, null=True)
    d8_l4 = models.TextField(blank=True, null=True)
    d8_l5 = models.TextField(blank=True, null=True)
    dim9 = models.TextField(blank=True, null=True)
    d9_l1 = models.TextField(blank=True, null=True)
    d9_l2 = models.TextField(blank=True, null=True)
    d9_l3 = models.TextField(blank=True, null=True)
    d9_l4 = models.TextField(blank=True, null=True)
    d9_l5 = models.TextField(blank=True, null=True)
    dim10 = models.TextField(blank=True, null=True)
    d10_l1 = models.TextField(blank=True, null=True)
    d10_l2 = models.TextField(blank=True, null=True)
    d10_l3 = models.TextField(blank=True, null=True)
    d10_l4 = models.TextField(blank=True, null=True)
    d10_l5 = models.TextField(blank=True, null=True)
    dim11 = models.TextField(blank=True, null=True)
    d11_l1 = models.TextField(blank=True, null=True)
    d11_l2 = models.TextField(blank=True, null=True)
    d11_l3 = models.TextField(blank=True, null=True)
    d11_l4 = models.TextField(blank=True, null=True)
    d11_l5 = models.TextField(blank=True, null=True)
    dim12 = models.TextField(blank=True, null=True)
    d12_l1 = models.TextField(blank=True, null=True)
    d12_l2 = models.TextField(blank=True, null=True)
    d12_l3 = models.TextField(blank=True, null=True)
    d12_l4 = models.TextField(blank=True, null=True)
    d12_l5 = models.TextField(blank=True, null=True)
    dim13 = models.TextField(blank=True, null=True)
    d13_l1 = models.TextField(blank=True, null=True)
    d13_l2 = models.TextField(blank=True, null=True)
    d13_l3 = models.TextField(blank=True, null=True)
    d13_l4 = models.TextField(blank=True, null=True)
    d13_l5 = models.TextField(blank=True, null=True)
    dim14 = models.TextField(blank=True, null=True)
    d14_l1 = models.TextField(blank=True, null=True)
    d14_l2 = models.TextField(blank=True, null=True)
    d14_l3 = models.TextField(blank=True, null=True)
    d14_l4 = models.TextField(blank=True, null=True)
    d14_l5 = models.TextField(blank=True, null=True)
    dim15 = models.TextField(blank=True, null=True)
    d15_l1 = models.TextField(blank=True, null=True)
    d15_l2 = models.TextField(blank=True, null=True)
    d15_l3 = models.TextField(blank=True, null=True)
    d15_l4 = models.TextField(blank=True, null=True)
    d15_l5 = models.TextField(blank=True, null=True)
    dict_filename = models.ForeignKey(DimenMap, on_delete=models.CASCADE)

    def __unicode__(self):
        return unicode(self.id)


class TaggedDataUpl(models.Model):
    dim1 = models.TextField(blank=True, null=True)
    d1_l1 = models.TextField(blank=True, null=True)
    d1_l2 = models.TextField(blank=True, null=True)
    d1_l3 = models.TextField(blank=True, null=True)
    d1_l4 = models.TextField(blank=True, null=True)
    d1_l5 = models.TextField(blank=True, null=True)
    dim2 = models.TextField(blank=True, null=True)
    d2_l1 = models.TextField(blank=True, null=True)
    d2_l2 = models.TextField(blank=True, null=True)
    d2_l3 = models.TextField(blank=True, null=True)
    d2_l4 = models.TextField(blank=True, null=True)
    d2_l5 = models.TextField(blank=True, null=True)
    dim3 = models.TextField(blank=True, null=True)
    d3_l1 = models.TextField(blank=True, null=True)
    d3_l2 = models.TextField(blank=True, null=True)
    d3_l3 = models.TextField(blank=True, null=True)
    d3_l4 = models.TextField(blank=True, null=True)
    d3_l5 = models.TextField(blank=True, null=True)
    dim4 = models.TextField(blank=True, null=True)
    d4_l1 = models.TextField(blank=True, null=True)
    d4_l2 = models.TextField(blank=True, null=True)
    d4_l3 = models.TextField(blank=True, null=True)
    d4_l4 = models.TextField(blank=True, null=True)
    d4_l5 = models.TextField(blank=True, null=True)
    dim5 = models.TextField(blank=True, null=True)
    d5_l1 = models.TextField(blank=True, null=True)
    d5_l2 = models.TextField(blank=True, null=True)
    d5_l3 = models.TextField(blank=True, null=True)
    d5_l4 = models.TextField(blank=True, null=True)
    d5_l5 = models.TextField(blank=True, null=True)
    dim6 = models.TextField(blank=True, null=True)
    d6_l1 = models.TextField(blank=True, null=True)
    d6_l2 = models.TextField(blank=True, null=True)
    d6_l3 = models.TextField(blank=True, null=True)
    d6_l4 = models.TextField(blank=True, null=True)
    d6_l5 = models.TextField(blank=True, null=True)
    dim7 = models.TextField(blank=True, null=True)
    d7_l1 = models.TextField(blank=True, null=True)
    d7_l2 = models.TextField(blank=True, null=True)
    d7_l3 = models.TextField(blank=True, null=True)
    d7_l4 = models.TextField(blank=True, null=True)
    d7_l5 = models.TextField(blank=True, null=True)
    dim8 = models.TextField(blank=True, null=True)
    d8_l1 = models.TextField(blank=True, null=True)
    d8_l2 = models.TextField(blank=True, null=True)
    d8_l3 = models.TextField(blank=True, null=True)
    d8_l4 = models.TextField(blank=True, null=True)
    d8_l5 = models.TextField(blank=True, null=True)
    dim9 = models.TextField(blank=True, null=True)
    d9_l1 = models.TextField(blank=True, null=True)
    d9_l2 = models.TextField(blank=True, null=True)
    d9_l3 = models.TextField(blank=True, null=True)
    d9_l4 = models.TextField(blank=True, null=True)
    d9_l5 = models.TextField(blank=True, null=True)
    dim10 = models.TextField(blank=True, null=True)
    d10_l1 = models.TextField(blank=True, null=True)
    d10_l2 = models.TextField(blank=True, null=True)
    d10_l3 = models.TextField(blank=True, null=True)
    d10_l4 = models.TextField(blank=True, null=True)
    d10_l5 = models.TextField(blank=True, null=True)
    dim11 = models.TextField(blank=True, null=True)
    d11_l1 = models.TextField(blank=True, null=True)
    d11_l2 = models.TextField(blank=True, null=True)
    d11_l3 = models.TextField(blank=True, null=True)
    d11_l4 = models.TextField(blank=True, null=True)
    d11_l5 = models.TextField(blank=True, null=True)
    dim12 = models.TextField(blank=True, null=True)
    d12_l1 = models.TextField(blank=True, null=True)
    d12_l2 = models.TextField(blank=True, null=True)
    d12_l3 = models.TextField(blank=True, null=True)
    d12_l4 = models.TextField(blank=True, null=True)
    d12_l5 = models.TextField(blank=True, null=True)
    dim13 = models.TextField(blank=True, null=True)
    d13_l1 = models.TextField(blank=True, null=True)
    d13_l2 = models.TextField(blank=True, null=True)
    d13_l3 = models.TextField(blank=True, null=True)
    d13_l4 = models.TextField(blank=True, null=True)
    d13_l5 = models.TextField(blank=True, null=True)
    dim14 = models.TextField(blank=True, null=True)
    d14_l1 = models.TextField(blank=True, null=True)
    d14_l2 = models.TextField(blank=True, null=True)
    d14_l3 = models.TextField(blank=True, null=True)
    d14_l4 = models.TextField(blank=True, null=True)
    d14_l5 = models.TextField(blank=True, null=True)
    dim15 = models.TextField(blank=True, null=True)
    d15_l1 = models.TextField(blank=True, null=True)
    d15_l2 = models.TextField(blank=True, null=True)
    d15_l3 = models.TextField(blank=True, null=True)
    d15_l4 = models.TextField(blank=True, null=True)
    d15_l5 = models.TextField(blank=True, null=True)
    rid = models.ForeignKey(Uploads, on_delete=models.CASCADE)
    dataset_filename = models.CharField(max_length=255)
    ngram = models.CharField(max_length=155, blank=True, null=True)

    def __unicode__(self):
        return unicode(self.id)


class AggTaggedDataUpl(models.Model):
    dataset_filename = models.CharField(max_length=255)
    dim1 = models.TextField(blank=True, null=True)
    dim2 = models.TextField(blank=True, null=True)
    dim3 = models.TextField(blank=True, null=True)
    dim4 = models.TextField(blank=True, null=True)
    dim5 = models.TextField(blank=True, null=True)
    dim6 = models.TextField(blank=True, null=True)
    dim7 = models.TextField(blank=True, null=True)
    dim8 = models.TextField(blank=True, null=True)
    dim9 = models.TextField(blank=True, null=True)
    dim10 = models.TextField(blank=True, null=True)
    dim11 = models.TextField(blank=True, null=True)
    dim12 = models.TextField(blank=True, null=True)
    dim13 = models.TextField(blank=True, null=True)
    dim14 = models.TextField(blank=True, null=True)
    dim15 = models.TextField(blank=True, null=True)
    rid = models.ForeignKey(Uploads, on_delete=models.CASCADE)

    def __unicode__(self):
        return unicode(self.id)


class TagDicts(models.Model):
    ngram = models.CharField(max_length=155)
    dim1 = models.TextField(blank=True, null=True)
    d1_l1 = models.TextField(blank=True, null=True)
    d1_l2 = models.TextField(blank=True, null=True)
    d1_l3 = models.TextField(blank=True, null=True)
    d1_l4 = models.TextField(blank=True, null=True)
    d1_l5 = models.TextField(blank=True, null=True)
    dim2 = models.TextField(blank=True, null=True)
    d2_l1 = models.TextField(blank=True, null=True)
    d2_l2 = models.TextField(blank=True, null=True)
    d2_l3 = models.TextField(blank=True, null=True)
    d2_l4 = models.TextField(blank=True, null=True)
    d2_l5 = models.TextField(blank=True, null=True)
    dim3 = models.TextField(blank=True, null=True)
    d3_l1 = models.TextField(blank=True, null=True)
    d3_l2 = models.TextField(blank=True, null=True)
    d3_l3 = models.TextField(blank=True, null=True)
    d3_l4 = models.TextField(blank=True, null=True)
    d3_l5 = models.TextField(blank=True, null=True)
    dim4 = models.TextField(blank=True, null=True)
    d4_l1 = models.TextField(blank=True, null=True)
    d4_l2 = models.TextField(blank=True, null=True)
    d4_l3 = models.TextField(blank=True, null=True)
    d4_l4 = models.TextField(blank=True, null=True)
    d4_l5 = models.TextField(blank=True, null=True)
    dim5 = models.TextField(blank=True, null=True)
    d5_l1 = models.TextField(blank=True, null=True)
    d5_l2 = models.TextField(blank=True, null=True)
    d5_l3 = models.TextField(blank=True, null=True)
    d5_l4 = models.TextField(blank=True, null=True)
    d5_l5 = models.TextField(blank=True, null=True)
    dim6 = models.TextField(blank=True, null=True)
    d6_l1 = models.TextField(blank=True, null=True)
    d6_l2 = models.TextField(blank=True, null=True)
    d6_l3 = models.TextField(blank=True, null=True)
    d6_l4 = models.TextField(blank=True, null=True)
    d6_l5 = models.TextField(blank=True, null=True)
    dim7 = models.TextField(blank=True, null=True)
    d7_l1 = models.TextField(blank=True, null=True)
    d7_l2 = models.TextField(blank=True, null=True)
    d7_l3 = models.TextField(blank=True, null=True)
    d7_l4 = models.TextField(blank=True, null=True)
    d7_l5 = models.TextField(blank=True, null=True)
    dim8 = models.TextField(blank=True, null=True)
    d8_l1 = models.TextField(blank=True, null=True)
    d8_l2 = models.TextField(blank=True, null=True)
    d8_l3 = models.TextField(blank=True, null=True)
    d8_l4 = models.TextField(blank=True, null=True)
    d8_l5 = models.TextField(blank=True, null=True)
    dim9 = models.TextField(blank=True, null=True)
    d9_l1 = models.TextField(blank=True, null=True)
    d9_l2 = models.TextField(blank=True, null=True)
    d9_l3 = models.TextField(blank=True, null=True)
    d9_l4 = models.TextField(blank=True, null=True)
    d9_l5 = models.TextField(blank=True, null=True)
    dim10 = models.TextField(blank=True, null=True)
    d10_l1 = models.TextField(blank=True, null=True)
    d10_l2 = models.TextField(blank=True, null=True)
    d10_l3 = models.TextField(blank=True, null=True)
    d10_l4 = models.TextField(blank=True, null=True)
    d10_l5 = models.TextField(blank=True, null=True)
    dim11 = models.TextField(blank=True, null=True)
    d11_l1 = models.TextField(blank=True, null=True)
    d11_l2 = models.TextField(blank=True, null=True)
    d11_l3 = models.TextField(blank=True, null=True)
    d11_l4 = models.TextField(blank=True, null=True)
    d11_l5 = models.TextField(blank=True, null=True)
    dim12 = models.TextField(blank=True, null=True)
    d12_l1 = models.TextField(blank=True, null=True)
    d12_l2 = models.TextField(blank=True, null=True)
    d12_l3 = models.TextField(blank=True, null=True)
    d12_l4 = models.TextField(blank=True, null=True)
    d12_l5 = models.TextField(blank=True, null=True)
    dim13 = models.TextField(blank=True, null=True)
    d13_l1 = models.TextField(blank=True, null=True)
    d13_l2 = models.TextField(blank=True, null=True)
    d13_l3 = models.TextField(blank=True, null=True)
    d13_l4 = models.TextField(blank=True, null=True)
    d13_l5 = models.TextField(blank=True, null=True)
    dim14 = models.TextField(blank=True, null=True)
    d14_l1 = models.TextField(blank=True, null=True)
    d14_l2 = models.TextField(blank=True, null=True)
    d14_l3 = models.TextField(blank=True, null=True)
    d14_l4 = models.TextField(blank=True, null=True)
    d14_l5 = models.TextField(blank=True, null=True)
    dim15 = models.TextField(blank=True, null=True)
    d15_l1 = models.TextField(blank=True, null=True)
    d15_l2 = models.TextField(blank=True, null=True)
    d15_l3 = models.TextField(blank=True, null=True)
    d15_l4 = models.TextField(blank=True, null=True)
    d15_l5 = models.TextField(blank=True, null=True)
    dict_filename = models.ForeignKey(DimenMap, on_delete=models.CASCADE)

    def __unicode__(self):
        return unicode(self.id)


class Social(models.Model):
    aid = models.CharField(primary_key=True, max_length=255)
    dataset_filename = models.CharField(max_length=255)
    rid = models.CharField(max_length=155)
    rTitle = models.TextField(null=True, blank=True)
    rUser = models.TextField(null=True, blank=True)
    rText = models.TextField(null=True, blank=True)
    rURL = models.TextField(null=True, blank=True)
    rRating = models.DecimalField(max_digits=2, decimal_places=1, null=False, default=0.0, blank=True)
    MEDIA_PROVIDER = models.TextField(null=True, blank=True)
    rDate = UnixDateTimeField(null=True, blank=True)
    rDate2 = models.DateField(null=True, blank=True)
    VIEW_COUNT = models.IntegerField(null=True, blank=True)
    COMMENT_COUNT = models.IntegerField(null=True, blank=True)
    UNIQUE_COMMENTERS = models.IntegerField(null=True, blank=True)
    ENGAGEMENT = models.IntegerField(null=True, blank=True)
    LINKS_AND_VOTES = models.IntegerField(null=True, blank=True)
    INBOUND_LINKS = models.IntegerField(null=True, blank=True)
    FORUM_THREAD_SIZE = models.IntegerField(null=True, blank=True)
    FOLLOWING = models.IntegerField(null=True, blank=True)
    FOLLOWERS = models.IntegerField(null=True, blank=True)
    UPDATES = models.IntegerField(null=True, blank=True)
    BLOG_POST_SENTIMENT = models.CharField(max_length=45, null=True, blank=True)
    dt = models.CharField(max_length=2, blank=True, null=True)
    mth = models.CharField(max_length=2, blank=True, null=True)
    year = models.CharField(max_length=4, blank=True, null=True)


class TaggedData(models.Model):
    dataset_filename = models.CharField(max_length=255,null=False)
    rid = models.CharField(max_length=155, null=False)
    dim1 = models.TextField(blank=True, null=True)
    d1_l1 = models.TextField(blank=True, null=True)
    d1_l2 = models.TextField(blank=True, null=True)
    d1_l3 = models.TextField(blank=True, null=True)
    d1_l4 = models.TextField(blank=True, null=True)
    d1_l5 = models.TextField(blank=True, null=True)
    dim2 = models.TextField(blank=True, null=True)
    d2_l1 = models.TextField(blank=True, null=True)
    d2_l2 = models.TextField(blank=True, null=True)
    d2_l3 = models.TextField(blank=True, null=True)
    d2_l4 = models.TextField(blank=True, null=True)
    d2_l5 = models.TextField(blank=True, null=True)
    dim3 = models.TextField(blank=True, null=True)
    d3_l1 = models.TextField(blank=True, null=True)
    d3_l2 = models.TextField(blank=True, null=True)
    d3_l3 = models.TextField(blank=True, null=True)
    d3_l4 = models.TextField(blank=True, null=True)
    d3_l5 = models.TextField(blank=True, null=True)
    dim4 = models.TextField(blank=True, null=True)
    d4_l1 = models.TextField(blank=True, null=True)
    d4_l2 = models.TextField(blank=True, null=True)
    d4_l3 = models.TextField(blank=True, null=True)
    d4_l4 = models.TextField(blank=True, null=True)
    d4_l5 = models.TextField(blank=True, null=True)
    dim5 = models.TextField(blank=True, null=True)
    d5_l1 = models.TextField(blank=True, null=True)
    d5_l2 = models.TextField(blank=True, null=True)
    d5_l3 = models.TextField(blank=True, null=True)
    d5_l4 = models.TextField(blank=True, null=True)
    d5_l5 = models.TextField(blank=True, null=True)
    dim6 = models.TextField(blank=True, null=True)
    d6_l1 = models.TextField(blank=True, null=True)
    d6_l2 = models.TextField(blank=True, null=True)
    d6_l3 = models.TextField(blank=True, null=True)
    d6_l4 = models.TextField(blank=True, null=True)
    d6_l5 = models.TextField(blank=True, null=True)
    dim7 = models.TextField(blank=True, null=True)
    d7_l1 = models.TextField(blank=True, null=True)
    d7_l2 = models.TextField(blank=True, null=True)
    d7_l3 = models.TextField(blank=True, null=True)
    d7_l4 = models.TextField(blank=True, null=True)
    d7_l5 = models.TextField(blank=True, null=True)
    dim8 = models.TextField(blank=True, null=True)
    d8_l1 = models.TextField(blank=True, null=True)
    d8_l2 = models.TextField(blank=True, null=True)
    d8_l3 = models.TextField(blank=True, null=True)
    d8_l4 = models.TextField(blank=True, null=True)
    d8_l5 = models.TextField(blank=True, null=True)
    dim9 = models.TextField(blank=True, null=True)
    d9_l1 = models.TextField(blank=True, null=True)
    d9_l2 = models.TextField(blank=True, null=True)
    d9_l3 = models.TextField(blank=True, null=True)
    d9_l4 = models.TextField(blank=True, null=True)
    d9_l5 = models.TextField(blank=True, null=True)
    dim10 = models.TextField(blank=True, null=True)
    d10_l1 = models.TextField(blank=True, null=True)
    d10_l2 = models.TextField(blank=True, null=True)
    d10_l3 = models.TextField(blank=True, null=True)
    d10_l4 = models.TextField(blank=True, null=True)
    d10_l5 = models.TextField(blank=True, null=True)
    dim11 = models.TextField(blank=True, null=True)
    d11_l1 = models.TextField(blank=True, null=True)
    d11_l2 = models.TextField(blank=True, null=True)
    d11_l3 = models.TextField(blank=True, null=True)
    d11_l4 = models.TextField(blank=True, null=True)
    d11_l5 = models.TextField(blank=True, null=True)
    dim12 = models.TextField(blank=True, null=True)
    d12_l1 = models.TextField(blank=True, null=True)
    d12_l2 = models.TextField(blank=True, null=True)
    d12_l3 = models.TextField(blank=True, null=True)
    d12_l4 = models.TextField(blank=True, null=True)
    d12_l5 = models.TextField(blank=True, null=True)
    dim13 = models.TextField(blank=True, null=True)
    d13_l1 = models.TextField(blank=True, null=True)
    d13_l2 = models.TextField(blank=True, null=True)
    d13_l3 = models.TextField(blank=True, null=True)
    d13_l4 = models.TextField(blank=True, null=True)
    d13_l5 = models.TextField(blank=True, null=True)
    dim14 = models.TextField(blank=True, null=True)
    d14_l1 = models.TextField(blank=True, null=True)
    d14_l2 = models.TextField(blank=True, null=True)
    d14_l3 = models.TextField(blank=True, null=True)
    d14_l4 = models.TextField(blank=True, null=True)
    d14_l5 = models.TextField(blank=True, null=True)
    dim15 = models.TextField(blank=True, null=True)
    d15_l1 = models.TextField(blank=True, null=True)
    d15_l2 = models.TextField(blank=True, null=True)
    d15_l3 = models.TextField(blank=True, null=True)
    d15_l4 = models.TextField(blank=True, null=True)
    d15_l5 = models.TextField(blank=True, null=True)
    aid = models.ForeignKey(Social, on_delete=models.CASCADE)
    ngram = models.CharField(max_length=155, blank=True, null=True)

    def __unicode__(self):
        return unicode(self.id)


class AggTaggedData(models.Model):
    dataset_filename = models.CharField(max_length=255, null=False)
    rid = models.CharField(max_length=155, null=False)
    dim1 = models.TextField(blank=True, null=True)
    dim2 = models.TextField(blank=True, null=True)
    dim3 = models.TextField(blank=True, null=True)
    dim4 = models.TextField(blank=True, null=True)
    dim5 = models.TextField(blank=True, null=True)
    dim6 = models.TextField(blank=True, null=True)
    dim7 = models.TextField(blank=True, null=True)
    dim8 = models.TextField(blank=True, null=True)
    dim9 = models.TextField(blank=True, null=True)
    dim10 = models.TextField(blank=True, null=True)
    dim11 = models.TextField(blank=True, null=True)
    dim12 = models.TextField(blank=True, null=True)
    dim13 = models.TextField(blank=True, null=True)
    dim14 = models.TextField(blank=True, null=True)
    dim15 = models.TextField(blank=True, null=True)
    aid = models.ForeignKey(Social, on_delete=models.CASCADE)

    def __unicode__(self):
        return unicode(self.id)


class SocialAnalyses(models.Model):
    rid = models.CharField(max_length=155, null=False)
    sentiment = models.CharField(max_length=20, blank=True, null=True)
    sentiScore = models.DecimalField(max_digits=4, decimal_places=2, blank=True, null=True)
    trigger = models.CharField(max_length=200, blank=True, null=True)
    driver = models.CharField(max_length=200, blank=True, null=True)
    aid = models.ForeignKey(Social, on_delete=models.CASCADE)

    def __unicode__(self):
        return unicode(self.id)


class ContentCategorySoc(models.Model):
    category_pri = models.CharField(max_length=200, blank=True, null=True)
    category_sec = models.CharField(max_length=200, blank=True, null=True)
    category_ter = models.CharField(max_length=200, blank=True, null=True)
    confidence = models.DecimalField(max_digits=4, decimal_places=2, blank=True, null=True)
    rid = models.ForeignKey(Social, on_delete=models.CASCADE)

    def __unicode__(self):
        return unicode(self.id)

#
# class AuthGroup(models.Model):
#     name = models.CharField(unique=True, max_length=80)
#
#     class Meta:
#         managed = False
#         db_table = 'auth_group'
#
#
# class AuthGroupPermissions(models.Model):
#     group = models.ForeignKey(AuthGroup, models.DO_NOTHING)
#     permission = models.ForeignKey('AuthPermission', models.DO_NOTHING)
#
#     class Meta:
#         managed = False
#         db_table = 'auth_group_permissions'
#         unique_together = (('group', 'permission'),)
#
#
# class AuthPermission(models.Model):
#     name = models.CharField(max_length=50)
#     content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING)
#     codename = models.CharField(max_length=100)
#
#     class Meta:
#         managed = False
#         db_table = 'auth_permission'
#         unique_together = (('content_type', 'codename'),)
#
#
# class AuthUser(models.Model):
#     password = models.CharField(max_length=128)
#     last_login = models.DateTimeField()
#     is_superuser = models.IntegerField()
#     username = models.CharField(unique=True, max_length=30)
#     first_name = models.CharField(max_length=30)
#     last_name = models.CharField(max_length=30)
#     email = models.CharField(max_length=75)
#     is_staff = models.IntegerField()
#     is_active = models.IntegerField()
#     date_joined = models.DateTimeField()
#
#     class Meta:
#         managed = False
#         db_table = 'auth_user'
#
#
# class AuthUserGroups(models.Model):
#     user = models.ForeignKey(AuthUser, models.DO_NOTHING)
#     group = models.ForeignKey(AuthGroup, models.DO_NOTHING)
#
#     class Meta:
#         managed = False
#         db_table = 'auth_user_groups'
#         unique_together = (('user', 'group'),)
#
#
# class AuthUserUserPermissions(models.Model):
#     user = models.ForeignKey(AuthUser, models.DO_NOTHING)
#     permission = models.ForeignKey(AuthPermission, models.DO_NOTHING)
#
#     class Meta:
#         managed = False
#         db_table = 'auth_user_user_permissions'
#         unique_together = (('user', 'permission'),)
#
#
# class DjangoAdminLog(models.Model):
#     action_time = models.DateTimeField()
#     object_id = models.TextField(blank=True, null=True)
#     object_repr = models.CharField(max_length=200)
#     action_flag = models.SmallIntegerField()
#     change_message = models.TextField()
#     content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING, blank=True, null=True)
#     user = models.ForeignKey(AuthUser, models.DO_NOTHING)
#
#     class Meta:
#         managed = False
#         db_table = 'django_admin_log'
#
#
# class DjangoContentType(models.Model):
#     name = models.CharField(max_length=100)
#     app_label = models.CharField(max_length=100)
#     model = models.CharField(max_length=100)
#
#     class Meta:
#         managed = False
#         db_table = 'django_content_type'
#         unique_together = (('app_label', 'model'),)
#
#
# class DjangoMigrations(models.Model):
#     app = models.CharField(max_length=255)
#     name = models.CharField(max_length=255)
#     applied = models.DateTimeField()
#
#     class Meta:
#         managed = False
#         db_table = 'django_migrations'
