dict = dict(logUrl=r'./atlas/PyScripts/Outputs/Log/',
            #outputUrl=r'./atlas/database/ATLAS_Universal_2.csv',
            outputPath=r'./atlas/database/Outputs/',
            requestUrl=r'./atlas/database/request.csv',
            amazonOutput=r'./atlas/database/Outputs/Amazon/',
            #homedepotOutput='./atlas/database/Outputs/HomeDepot/',
            #walmartOutput='./atlas/database/Outputs/Walmart/',
            #chromeDriver=r'/home/vmagent/app/atlas/chromedriver',
            #chromeBrowser=r'/home/vmagent/app/atlas/chrome',
            keywordsDict=r'./atlas/database/keywordsSubTD.csv',
            tagDict=r'./atlas/database/TaggingDicts/electronics_dict.csv',
            tagDictPath=r'./atlas/database/TaggingDicts/',
            tdDictsPath=r'./atlas/database/TrigDrivDicts/',
            tri_dri_Output=r'./atlas/database/Outputs/Triggers-Drivers/',
            sentDict=r'./atlas/database/AFINN-111.txt',
            sentDictsPath=r'./atlas/database/SentiDicts/',
            uploadsUrl=r'./atlas/database/uploads/',
            topicViz=r'./atlas/templates/atlas/includes/',
            topicModels=r'./atlas/database/topicmodel/models/',
            logosPath=r'./atlas/static/atlas/images/icons/',
            sourcesUrl=r'./atlas/database/sourceMap.csv',
            dbfolderPath=r'./atlas/database/',
            associationInput = r'./atlas/database/fashion_brands.csv',
			spiderPath = r'./atlas/scrapers/scrapers/spiders/',
            gcp_servicekey_path = r'./gcp-servicekey.json'
            )
